config/routes.rb
Rails.application.routes.draw do
  resources :faq_items
  resources :faq_sections
  resources :pricing_capabilities
  resources :capabilities
  resources :pricing_items
  resources :pricing_sections
  resources :team_items
  resources :team_sections
  resources :portfolio_items
  resources :portfolio_categories
  resources :portfolio_sections
  resources :testimonial_items
  resources :testimonial_sections
  resources :feature_items
  resources :feature_sections
  resources :grid_service_items
  resources :horizon_service_items
  resources :service_sections
  resources :about_us_sections
  resources :clients
  resources :sections
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "visitors#index"
  post 'visitors/submit_contact_form'
end

app/models/grid_service_item.rb
# == Schema Information
#
# Table name: grid_service_items
#
#  id                 :bigint           not null, primary key
#  service_section_id :bigint
#  position           :integer
#  header             :string
#  description        :string
#  active             :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class GridServiceItem < ApplicationRecord
  belongs_to :service_section
  scope :active, -> {where('active = ?', true).order(:position)}
end

app/controllers/grid_service_items_controller.rb
class GridServiceItemsController < ApplicationController
  before_action :set_grid_service_item, only: %i[ show edit update destroy ]

  # GET /grid_service_items or /grid_service_items.json
  def index
    @grid_service_items = GridServiceItem.all
  end

  # GET /grid_service_items/1 or /grid_service_items/1.json
  def show
  end

  # GET /grid_service_items/new
  def new
    @grid_service_item = GridServiceItem.new
  end

  # GET /grid_service_items/1/edit
  def edit
  end

  # POST /grid_service_items or /grid_service_items.json
  def create
    @grid_service_item = GridServiceItem.new(grid_service_item_params)

    respond_to do |format|
      if @grid_service_item.save
        format.html { redirect_to @grid_service_item, notice: "Grid service item was successfully created." }
        format.json { render :show, status: :created, location: @grid_service_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grid_service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grid_service_items/1 or /grid_service_items/1.json
  def update
    respond_to do |format|
      if @grid_service_item.update(grid_service_item_params)
        format.html { redirect_to @grid_service_item, notice: "Grid service item was successfully updated." }
        format.json { render :show, status: :ok, location: @grid_service_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grid_service_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grid_service_items/1 or /grid_service_items/1.json
  def destroy
    @grid_service_item.destroy
    respond_to do |format|
      format.html { redirect_to grid_service_items_url, notice: "Grid service item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grid_service_item
      @grid_service_item = GridServiceItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grid_service_item_params
      params.require(:grid_service_item).permit(:service_section_id, :position, :header, :description, :active)
    end
end

app/helpers/grid_service_items_helper.rb
module GridServiceItemsHelper
end

app/views/grid_service_items/_form.html.erb
<%= form_with(model: grid_service_item, local: true) do |form| %>
  <% if grid_service_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grid_service_item.errors.count, "error") %> prohibited this grid_service_item from being saved:</h2>

      <ul>
      <% grid_service_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :service_section_id %>
    <%= form.text_field :service_section_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grid_service_items/edit.html.erb
<h1>Editing Grid Service Item</h1>

<%= render 'form', grid_service_item: @grid_service_item %>

<%= link_to 'Show', @grid_service_item %> |
<%= link_to 'Back', grid_service_items_path %>

app/views/grid_service_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grid Service Items</h1>

<table>
  <thead>
    <tr>
      <th>Service section</th>
      <th>Position</th>
      <th>Header</th>
      <th>Description</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grid_service_items.each do |grid_service_item| %>
      <tr>
        <td><%= grid_service_item.service_section %></td>
        <td><%= grid_service_item.position %></td>
        <td><%= grid_service_item.header %></td>
        <td><%= grid_service_item.description %></td>
        <td><%= grid_service_item.active %></td>
        <td><%= link_to 'Show', grid_service_item %></td>
        <td><%= link_to 'Edit', edit_grid_service_item_path(grid_service_item) %></td>
        <td><%= link_to 'Destroy', grid_service_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grid Service Item', new_grid_service_item_path %>

app/views/grid_service_items/new.html.erb
<h1>New Grid Service Item</h1>

<%= render 'form', grid_service_item: @grid_service_item %>

<%= link_to 'Back', grid_service_items_path %>

app/views/grid_service_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service section:</strong>
  <%= @grid_service_item.service_section %>
</p>

<p>
  <strong>Position:</strong>
  <%= @grid_service_item.position %>
</p>

<p>
  <strong>Header:</strong>
  <%= @grid_service_item.header %>
</p>

<p>
  <strong>Description:</strong>
  <%= @grid_service_item.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @grid_service_item.active %>
</p>

<%= link_to 'Edit', edit_grid_service_item_path(@grid_service_item) %> |
<%= link_to 'Back', grid_service_items_path %>