config/routes.rb
Rails.application.routes.draw do
  resources :faq_items
  resources :faq_sections
  resources :pricing_capabilities
  resources :capabilities
  resources :pricing_items
  resources :pricing_sections
  resources :team_items
  resources :team_sections
  resources :portfolio_items
  resources :portfolio_categories
  resources :portfolio_sections
  resources :testimonial_items
  resources :testimonial_sections
  resources :feature_items
  resources :feature_sections
  resources :grid_service_items
  resources :horizon_service_items
  resources :service_sections
  resources :about_us_sections
  resources :clients
  resources :sections
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "visitors#index"
  post 'visitors/submit_contact_form'
end

app/models/pricing_item.rb
# == Schema Information
#
# Table name: pricing_items
#
#  id                 :bigint           not null, primary key
#  pricing_section_id :bigint
#  position           :integer
#  name               :string
#  price              :decimal(10, 2)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class PricingItem < ApplicationRecord
  belongs_to :pricing_section
  has_many :pricing_capabilities, dependent: :destroy
  scope :ordered, -> {order(:position)}
end

app/controllers/pricing_items_controller.rb
class PricingItemsController < ApplicationController
  before_action :set_pricing_item, only: %i[ show edit update destroy ]

  # GET /pricing_items or /pricing_items.json
  def index
    @pricing_items = PricingItem.all
  end

  # GET /pricing_items/1 or /pricing_items/1.json
  def show
  end

  # GET /pricing_items/new
  def new
    @pricing_item = PricingItem.new
  end

  # GET /pricing_items/1/edit
  def edit
  end

  # POST /pricing_items or /pricing_items.json
  def create
    @pricing_item = PricingItem.new(pricing_item_params)

    respond_to do |format|
      if @pricing_item.save
        format.html { redirect_to @pricing_item, notice: "Pricing item was successfully created." }
        format.json { render :show, status: :created, location: @pricing_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pricing_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pricing_items/1 or /pricing_items/1.json
  def update
    respond_to do |format|
      if @pricing_item.update(pricing_item_params)
        format.html { redirect_to @pricing_item, notice: "Pricing item was successfully updated." }
        format.json { render :show, status: :ok, location: @pricing_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pricing_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pricing_items/1 or /pricing_items/1.json
  def destroy
    @pricing_item.destroy
    respond_to do |format|
      format.html { redirect_to pricing_items_url, notice: "Pricing item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pricing_item
      @pricing_item = PricingItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pricing_item_params
      params.require(:pricing_item).permit(:pricing_section_id, :position, :name, :price)
    end
end

app/helpers/pricing_items_helper.rb
module PricingItemsHelper
end

app/views/pricing_items/_form.html.erb
<%= form_with(model: pricing_item, local: true) do |form| %>
  <% if pricing_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pricing_item.errors.count, "error") %> prohibited this pricing_item from being saved:</h2>

      <ul>
      <% pricing_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pricing_section_id %>
    <%= form.text_field :pricing_section_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pricing_items/edit.html.erb
<h1>Editing Pricing Item</h1>

<%= render 'form', pricing_item: @pricing_item %>

<%= link_to 'Show', @pricing_item %> |
<%= link_to 'Back', pricing_items_path %>

app/views/pricing_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pricing Items</h1>

<table>
  <thead>
    <tr>
      <th>Pricing section</th>
      <th>Position</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pricing_items.each do |pricing_item| %>
      <tr>
        <td><%= pricing_item.pricing_section %></td>
        <td><%= pricing_item.position %></td>
        <td><%= pricing_item.name %></td>
        <td><%= pricing_item.price %></td>
        <td><%= link_to 'Show', pricing_item %></td>
        <td><%= link_to 'Edit', edit_pricing_item_path(pricing_item) %></td>
        <td><%= link_to 'Destroy', pricing_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pricing Item', new_pricing_item_path %>

app/views/pricing_items/new.html.erb
<h1>New Pricing Item</h1>

<%= render 'form', pricing_item: @pricing_item %>

<%= link_to 'Back', pricing_items_path %>

app/views/pricing_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pricing section:</strong>
  <%= @pricing_item.pricing_section %>
</p>

<p>
  <strong>Position:</strong>
  <%= @pricing_item.position %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pricing_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pricing_item.price %>
</p>

<%= link_to 'Edit', edit_pricing_item_path(@pricing_item) %> |
<%= link_to 'Back', pricing_items_path %>