config/routes.rb
Rails.application.routes.draw do
  resources :faq_items
  resources :faq_sections
  resources :pricing_capabilities
  resources :capabilities
  resources :pricing_items
  resources :pricing_sections
  resources :team_items
  resources :team_sections
  resources :portfolio_items
  resources :portfolio_categories
  resources :portfolio_sections
  resources :testimonial_items
  resources :testimonial_sections
  resources :feature_items
  resources :feature_sections
  resources :grid_service_items
  resources :horizon_service_items
  resources :service_sections
  resources :about_us_sections
  resources :clients
  resources :sections
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "visitors#index"
  post 'visitors/submit_contact_form'
end

app/models/capability.rb
# == Schema Information
#
# Table name: capabilities
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Capability < ApplicationRecord
  has_many :pricing_capabilities, dependent: :restrict_with_error
end

app/controllers/capabilities_controller.rb
class CapabilitiesController < ApplicationController
  before_action :set_capability, only: %i[ show edit update destroy ]

  # GET /capabilities or /capabilities.json
  def index
    @capabilities = Capability.all
  end

  # GET /capabilities/1 or /capabilities/1.json
  def show
  end

  # GET /capabilities/new
  def new
    @capability = Capability.new
  end

  # GET /capabilities/1/edit
  def edit
  end

  # POST /capabilities or /capabilities.json
  def create
    @capability = Capability.new(capability_params)

    respond_to do |format|
      if @capability.save
        format.html { redirect_to @capability, notice: "Capability was successfully created." }
        format.json { render :show, status: :created, location: @capability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @capability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capabilities/1 or /capabilities/1.json
  def update
    respond_to do |format|
      if @capability.update(capability_params)
        format.html { redirect_to @capability, notice: "Capability was successfully updated." }
        format.json { render :show, status: :ok, location: @capability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @capability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capabilities/1 or /capabilities/1.json
  def destroy
    @capability.destroy
    respond_to do |format|
      format.html { redirect_to capabilities_url, notice: "Capability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capability
      @capability = Capability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def capability_params
      params.require(:capability).permit(:name)
    end
end

app/helpers/capabilities_helper.rb
module CapabilitiesHelper
end

app/views/capabilities/_form.html.erb
<%= form_with(model: capability, local: true) do |form| %>
  <% if capability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(capability.errors.count, "error") %> prohibited this capability from being saved:</h2>

      <ul>
      <% capability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/capabilities/edit.html.erb
<h1>Editing Capability</h1>

<%= render 'form', capability: @capability %>

<%= link_to 'Show', @capability %> |
<%= link_to 'Back', capabilities_path %>

app/views/capabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Capabilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capabilities.each do |capability| %>
      <tr>
        <td><%= capability.name %></td>
        <td><%= link_to 'Show', capability %></td>
        <td><%= link_to 'Edit', edit_capability_path(capability) %></td>
        <td><%= link_to 'Destroy', capability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capability', new_capability_path %>

app/views/capabilities/new.html.erb
<h1>New Capability</h1>

<%= render 'form', capability: @capability %>

<%= link_to 'Back', capabilities_path %>

app/views/capabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @capability.name %>
</p>

<%= link_to 'Edit', edit_capability_path(@capability) %> |
<%= link_to 'Back', capabilities_path %>