config/routes.rb
Rails.application.routes.draw do
  resources :faq_items
  resources :faq_sections
  resources :pricing_capabilities
  resources :capabilities
  resources :pricing_items
  resources :pricing_sections
  resources :team_items
  resources :team_sections
  resources :portfolio_items
  resources :portfolio_categories
  resources :portfolio_sections
  resources :testimonial_items
  resources :testimonial_sections
  resources :feature_items
  resources :feature_sections
  resources :grid_service_items
  resources :horizon_service_items
  resources :service_sections
  resources :about_us_sections
  resources :clients
  resources :sections
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "visitors#index"
  post 'visitors/submit_contact_form'
end

app/models/portfolio_item.rb
# == Schema Information
#
# Table name: portfolio_items
#
#  id                    :bigint           not null, primary key
#  portfolio_section_id  :bigint
#  position              :integer
#  portfolio_category_id :bigint
#  client_name           :string
#  project_date          :date
#  project_url           :string
#  description           :text
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  title                 :string
#

class PortfolioItem < ApplicationRecord
  belongs_to :portfolio_section
  belongs_to :portfolio_category
  scope :ordered, -> {order(:position)}
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :set_portfolio_item, only: %i[ show edit update destroy ]

  # GET /portfolio_items or /portfolio_items.json
  def index
    @portfolio_items = PortfolioItem.all
  end

  # GET /portfolio_items/1 or /portfolio_items/1.json
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = PortfolioItem.new
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items or /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: "Portfolio item was successfully created." }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_items/1 or /portfolio_items/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to @portfolio_item, notice: "Portfolio item was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1 or /portfolio_items/1.json
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_items_url, notice: "Portfolio item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_item_params
      params.require(:portfolio_item).permit(:portfolio_section_id, :position, :portfolio_category_id, :client_name, :project_date, :project_url, :description)
    end
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/views/portfolio_items/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited this portfolio_item from being saved:</h2>

      <ul>
      <% portfolio_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :portfolio_section_id %>
    <%= form.text_field :portfolio_section_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :portfolio_category_id %>
    <%= form.text_field :portfolio_category_id %>
  </div>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :project_date %>
    <%= form.date_select :project_date %>
  </div>

  <div class="field">
    <%= form.label :project_url %>
    <%= form.text_field :project_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolio_items/edit.html.erb
<h1>Editing Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<%= link_to 'Show', @portfolio_item %> |
<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolio Items</h1>

<table>
  <thead>
    <tr>
      <th>Portfolio section</th>
      <th>Position</th>
      <th>Portfolio category</th>
      <th>Client name</th>
      <th>Project date</th>
      <th>Project url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_items.each do |portfolio_item| %>
      <tr>
        <td><%= portfolio_item.portfolio_section %></td>
        <td><%= portfolio_item.position %></td>
        <td><%= portfolio_item.portfolio_category %></td>
        <td><%= portfolio_item.client_name %></td>
        <td><%= portfolio_item.project_date %></td>
        <td><%= portfolio_item.project_url %></td>
        <td><%= portfolio_item.description %></td>
        <td><%= link_to 'Show', portfolio_item %></td>
        <td><%= link_to 'Edit', edit_portfolio_item_path(portfolio_item) %></td>
        <td><%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio Item', new_portfolio_item_path %>

app/views/portfolio_items/new.html.erb
<h1>New Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<%= link_to 'Back', portfolio_items_path %>

app/views/portfolio_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Portfolio section:</strong>
  <%= @portfolio_item.portfolio_section %>
</p>

<p>
  <strong>Position:</strong>
  <%= @portfolio_item.position %>
</p>

<p>
  <strong>Portfolio category:</strong>
  <%= @portfolio_item.portfolio_category %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @portfolio_item.client_name %>
</p>

<p>
  <strong>Project date:</strong>
  <%= @portfolio_item.project_date %>
</p>

<p>
  <strong>Project url:</strong>
  <%= @portfolio_item.project_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio_item.description %>
</p>

<%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item) %> |
<%= link_to 'Back', portfolio_items_path %>